### ISSUE TITLE
CarrierWave::ProcessingError unable to open image `/tmp/magick-6No4015N4HWij': No such file or directory @ error/blob.c/OpenBlob/2712

### ISSUE THREAD

**Issue by taichi-jp** [metaware/carrierwave-google-storage#30]
I'm suffering from this error. This occurs sometimes, not always. What is the cause of this?

```
Magick::ImageMagickError: unable to open image `/tmp/magick-6No4015N4HWij': No such file or directory @ error/blob.c/OpenBlob/2712
  from carrierwave/processing/rmagick.rb:352:in `read'
  from carrierwave/processing/rmagick.rb:352:in `manipulate!'
  from carrierwave/processing/rmagick.rb:202:in `resize_to_fill'
  from carrierwave/uploader/processing.rb:83:in `block (2 levels) in process!'
  from carrierwave/uploader/processing.rb:75:in `each'
  from carrierwave/uploader/processing.rb:75:in `block in process!'
  from carrierwave/uploader/callbacks.rb:15:in `with_callbacks'
  from carrierwave/uploader/processing.rb:74:in `process!'
  from backgrounder/delay.rb:14:in `process!'
  from carrierwave/uploader/callbacks.rb:14:in `block in with_callbacks'
  from carrierwave/uploader/callbacks.rb:14:in `each'
  from carrierwave/uploader/callbacks.rb:14:in `with_callbacks'
  from carrierwave/uploader/cache.rb:137:in `cache!'
  from carrierwave/uploader/versions.rb:275:in `block in cache_versions!'
  from carrierwave/uploader/versions.rb:273:in `each'
  from carrierwave/uploader/versions.rb:273:in `cache_versions!'
  from backgrounder/delay.rb:6:in `cache_versions!'
  from carrierwave/uploader/callbacks.rb:16:in `block in with_callbacks'
  from carrierwave/uploader/callbacks.rb:16:in `each'
  from carrierwave/uploader/callbacks.rb:16:in `with_callbacks'
  from carrierwave/uploader/cache.rb:137:in `cache!'
  from carrierwave/uploader/versions.rb:234:in `recreate_versions!'
  from backgrounder/workers/process_asset_mixin.rb:17:in `perform'
  from sidekiq/processor.rb:187:in `execute_job'
  from sidekiq/processor.rb:169:in `block (2 levels) in process'
  from sidekiq/middleware/chain.rb:128:in `block in invoke'
  from raven/integrations/sidekiq.rb:9:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/middleware/chain.rb:133:in `invoke'
  from sidekiq/processor.rb:168:in `block in process'
  from sidekiq/processor.rb:139:in `block (6 levels) in dispatch'
  from sidekiq/job_retry.rb:98:in `local'
  from sidekiq/processor.rb:138:in `block (5 levels) in dispatch'
  from sidekiq/rails.rb:42:in `block in call'
  from active_support/execution_wrapper.rb:85:in `wrap'
  from active_support/reloader.rb:68:in `block in wrap'
  from active_support/execution_wrapper.rb:85:in `wrap'
  from active_support/reloader.rb:67:in `wrap'
  from sidekiq/rails.rb:41:in `call'
  from sidekiq/processor.rb:134:in `block (4 levels) in dispatch'
  from sidekiq/processor.rb:199:in `stats'
  from sidekiq/processor.rb:129:in `block (3 levels) in dispatch'
  from sidekiq/job_logger.rb:8:in `call'
  from sidekiq/processor.rb:128:in `block (2 levels) in dispatch'
  from sidekiq/job_retry.rb:73:in `global'
  from sidekiq/processor.rb:127:in `block in dispatch'
  from sidekiq/logging.rb:48:in `with_context'
  from sidekiq/logging.rb:42:in `with_job_hash_context'
  from sidekiq/processor.rb:126:in `dispatch'
  from sidekiq/processor.rb:167:in `process'
  from sidekiq/processor.rb:85:in `process_one'
  from sidekiq/processor.rb:73:in `run'
  from sidekiq/util.rb:16:in `watchdog'
  from sidekiq/util.rb:25:in `block in safe_thread'
CarrierWave::ProcessingError: unable to open image `/tmp/magick-6No4015N4HWij': No such file or directory @ error/blob.c/OpenBlob/2712
  from carrierwave/processing/rmagick.rb:374:in `rescue in manipulate!'
  from carrierwave/processing/rmagick.rb:349:in `manipulate!'
  from carrierwave/processing/rmagick.rb:202:in `resize_to_fill'
  from carrierwave/uploader/processing.rb:83:in `block (2 levels) in process!'
  from carrierwave/uploader/processing.rb:75:in `each'
  from carrierwave/uploader/processing.rb:75:in `block in process!'
  from carrierwave/uploader/callbacks.rb:15:in `with_callbacks'
  from carrierwave/uploader/processing.rb:74:in `process!'
  from backgrounder/delay.rb:14:in `process!'
  from carrierwave/uploader/callbacks.rb:14:in `block in with_callbacks'
  from carrierwave/uploader/callbacks.rb:14:in `each'
  from carrierwave/uploader/callbacks.rb:14:in `with_callbacks'
  from carrierwave/uploader/cache.rb:137:in `cache!'
  from carrierwave/uploader/versions.rb:275:in `block in cache_versions!'
  from carrierwave/uploader/versions.rb:273:in `each'
  from carrierwave/uploader/versions.rb:273:in `cache_versions!'
  from backgrounder/delay.rb:6:in `cache_versions!'
  from carrierwave/uploader/callbacks.rb:16:in `block in with_callbacks'
  from carrierwave/uploader/callbacks.rb:16:in `each'
  from carrierwave/uploader/callbacks.rb:16:in `with_callbacks'
  from carrierwave/uploader/cache.rb:137:in `cache!'
  from carrierwave/uploader/versions.rb:234:in `recreate_versions!'
  from backgrounder/workers/process_asset_mixin.rb:17:in `perform'
  from sidekiq/processor.rb:187:in `execute_job'
  from sidekiq/processor.rb:169:in `block (2 levels) in process'
  from sidekiq/middleware/chain.rb:128:in `block in invoke'
  from raven/integrations/sidekiq.rb:9:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/middleware/chain.rb:133:in `invoke'
  from sidekiq/processor.rb:168:in `block in process'
  from sidekiq/processor.rb:139:in `block (6 levels) in dispatch'
  from sidekiq/job_retry.rb:98:in `local'
  from sidekiq/processor.rb:138:in `block (5 levels) in dispatch'
  from sidekiq/rails.rb:42:in `block in call'
  from active_support/execution_wrapper.rb:85:in `wrap'
  from active_support/reloader.rb:68:in `block in wrap'
  from active_support/execution_wrapper.rb:85:in `wrap'
  from active_support/reloader.rb:67:in `wrap'
  from sidekiq/rails.rb:41:in `call'
  from sidekiq/processor.rb:134:in `block (4 levels) in dispatch'
  from sidekiq/processor.rb:199:in `stats'
  from sidekiq/processor.rb:129:in `block (3 levels) in dispatch'
  from sidekiq/job_logger.rb:8:in `call'
  from sidekiq/processor.rb:128:in `block (2 levels) in dispatch'
  from sidekiq/job_retry.rb:73:in `global'
  from sidekiq/processor.rb:127:in `block in dispatch'
  from sidekiq/logging.rb:48:in `with_context'
  from sidekiq/logging.rb:42:in `with_job_hash_context'
  from sidekiq/processor.rb:126:in `dispatch'
  from sidekiq/processor.rb:167:in `process'
  from sidekiq/processor.rb:85:in `process_one'
  from sidekiq/processor.rb:73:in `run'
  from sidekiq/util.rb:16:in `watchdog'
  from sidekiq/util.rb:25:in `block in safe_thread'
```

My settings are like below.
```ruby
CarrierWave.configure do |config|
    config.gcloud_bucket                       = ENV.fetch("GCP_STORAGE_BUCKET_NAME", "")
    config.gcloud_bucket_is_public             = true
    config.gcloud_authenticated_url_expiration = 600
    config.gcloud_content_disposition          = "attachment"

    config.gcloud_attributes = {
      expires: 600
    }

    config.gcloud_credentials = {
      gcloud_project: "my_project_id",
      gcloud_keyfile: "credentials.json"
    }
  end
```

**Comment by ianrandmckenzie** [comment]
I am getting this as well when creating a Tempfile

**Comment by taichi-jp** [comment]
I'm too using Ruby on Rails on Ubuntu 16.04 and also using RMagick  internally.
I guess the tempfile is created automatically by ImageMagick or this library.

I cannot figure out why this error sometimes occurs

**Comment by jasdeepsingh** [comment]
Looks like this is an issue with Carrierwave and Rmagick and doesn't have anything to do with this library, hence closing. 
I suggest opening up an issue with Carrierwave. 

I welcome you to re-open the issue if it continues to be a problem.
